
name = "alemtydao"
main = "src/index.ts"
compatibility_date = "2026-04-11"

# ===============================
# Frontend (Static Assets / SPA)
# ===============================
[assets]
directory = "./public"
not_found_handling = "single-page-application"

# ===============================
# Database (D1)
# ===============================
[[d1_databases]]
binding = "DB"
database_name = "alemtydao-db"
database_id = "bd641541-fbee-4630-b13e-4af7683887fc"

# ===============================
# AURA Token Contract (Base Mainnet)
# ===============================
[vars]
AURA_CONTRACT = "0x74f685da4d39e53e7df6e0970b84224ea0d00634"
AURA_RPC_URL = "https://mainnet.base.org"
MINTER_ADDRESS = "0x6A202f991c4C1df079449BE9847b1DaC3F51854f"
DISTRIBUTOR_ADDRESS = "0x8ed91bc2777577f9e9694a60dff515da8d13c9ac"
